# Generated by Django 2.2.2 on 2019-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('actors', models.TextField()),
                ('runtime', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('metascore', models.FloatField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
